- name: Provision Physical Server
  hosts: all
  tasks:
    - name: provisioning physical server 
      debug:
        msg: "Provisioning physical Server over IPMI"
      when: IPMI_IP == True
      failed_when: IPMI_IP == False
